class Settings:
    SCREEN_WIDTH = 640
    SCREEN_HEIGHT = 640
    SCREEN_COLOR = (0, 0, 64)
    # TIMER SETTINGS
    TIMER_SIZE = (40, 40)
    TIMER_POSITION = (0,0)
    TIMER_FONT_SIZE = 25
    TIMER_STARTTIME = 10
    TIMER_BREAKTIME = 3

    GAME_TITLE = "Gravity Snails"
    GAME_PLAYERS = 2
    GAME_SNAILS = 2