class Settings:
    SCREEN_WIDTH = 640
    SCREEN_HEIGHT = 640
    
    # TIMER SETTINGS
    TIMER_SIZE = (40, 40)
    TIMER_POSITION = (0,0)
    TIMER_FONT_SIZE = 25
    TIMER_STARTTIME = 10
    TIMER_BREAKTIME = 3